spring.application.name=payment-service
server.port=8081
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

# AWS Configuration
aws.access.key=AKIAIOSFODNN7EXAMPLE
aws.secret.key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
payment.api.token=ghp_1234567890abcdefghijklmnopqrstuvwxyz

